name: "Test"

on:
  push:
    branches: [ main, develop ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main, develop ]

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:4.2
        ports:
          - 27017:27017
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.16'
      - name: Test
        run: |
          for pkg in apps; do
            go test ./${pkg}
          done
